# Generated by Django 6.1 on 2026-09-06 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_certificate_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('research_type', models.CharField(help_text='Example: Thesis, Journal Article, Conference Paper', max_length=100)),
                ('role', models.CharField(blank=True, help_text='Example: Researcher, Author, Adviser', max_length=100)),
                ('institution', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='Completed', max_length=50)),
                ('abstract', models.TextField(blank=True)),
                ('research_url', models.URLField(blank=True)),
                ('publication_url', models.URLField(blank=True)),
                ('collaborators', models.TextField(blank=True, help_text='List co-researchers or authors.')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research', to='portfolio.profile')),
            ],
            options={
                'ordering': ['-completion_date', 'title'],
            },
        ),
    ]
