# Generated by Django 6.1 on 2026-09-06 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_research'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('issuing_organization', models.CharField(max_length=200)),
                ('license_type', models.CharField(blank=True, help_text='Example: Professional License, Academic License, Teaching License', max_length=100)),
                ('license_number', models.CharField(blank=True, max_length=200)),
                ('issue_date', models.DateField()),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('license_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='portfolio.profile')),
            ],
            options={
                'ordering': ['-issue_date', 'name'],
            },
        ),
    ]
