# Generated by Django 6.1 on 2026-09-06 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_license'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('awarding_organization', models.CharField(max_length=200)),
                ('award_type', models.CharField(blank=True, help_text='Example: Academic, Professional, Research, Leadership', max_length=100)),
                ('award_date', models.DateField()),
                ('level', models.CharField(blank=True, help_text='Example: Institutional, Local, Regional, National, International', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('award_url', models.URLField(blank=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='portfolio.profile')),
            ],
            options={
                'ordering': ['-award_date', 'name'],
            },
        ),
    ]
