# Generated by Django 6.1 on 2026-09-06 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_award'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=200)),
                ('membership_type', models.CharField(blank=True, help_text='Example: Regular Member, Associate Member, Fellow, Student Member', max_length=100)),
                ('membership_number', models.CharField(blank=True, max_length=200)),
                ('role', models.CharField(blank=True, help_text='Example: Member, Officer, Board Member, Chapter President', max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('membership_url', models.URLField(blank=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_memberships', to='portfolio.profile')),
            ],
            options={
                'ordering': ['-start_date', 'organization_name'],
            },
        ),
    ]
