# Generated by Django 6.1 on 2026-09-07 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_engagement_management'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='evidence',
            new_name='evidence_visibility_idx',
            old_name='evidence_profile_visibility_idx',
        ),
        migrations.RemoveField(
            model_name='engagement',
            name='organizations',
        ),
    ]
